version: "3"

services:
  bridge-discord-bot:
    build: .
    container_name: deno-container
    image: deno-image
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./bot_data:/app/bot_data
  bridge-cron:
    build: .
    container_name: cron-container
    image: deno-image
    env_file:
      - .env
    command: sh -c "while true; do deno run -A src/cron.ts; sleep 300; done"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"